### ISSUE TITLE
Glitch occurs when using hotkeys against Cerulean Bell

### ISSUE THREAD

**Issue by JesseNoEyes** [Agoraaa/FlushHotkeys#1]
When playing against the Cerulean Bell boss blind that forces a card to be selected at all times, using the hotkeys in certain sequences can cause the forced card to be de-selected. Or sometimes pseudo-deselected, where it appears unselected but is in a glitched state where it is unselected and selected simultaneously and contributing to the current hand. Even after the boss is defeated, this and other cards glitch in your hand, sometimes appearing flipped over, invisible, or altogether unselectable. 
Huge fan of this mod, just thought I'd bring this to your attention. For the time being, I'll just select my cards with the mouse like a caveman during Cerulean Bell. Thanks for all you do!

**Comment by Agoraaa** [comment]
Thank you for your feedback! 

I pushed [this](https://github.com/Agoraaa/FlushHotkeys/commit/eb0336d46561cee9db4a061ea2a14929e432fc0a) commit that should fix the issue. Though I couldn't test it yet. Gonna close the issue after I finally find Cerulean Bell.
