### ISSUE TITLE
Balamod version

### ISSUE THREAD

**Issue by hazzuk** [Agoraaa/FlushHotkeys#7]
Hello, awesome mod! I play Balatro on my macbook sometimes and so I opted to use the Balamod mod loader. As Steamodded requires a much more complex setup, compared to when using it on Windows. As such it would be great to see this mod also have a version for the Balamod mod loader. Thank you for creating this mod.

- [Balamod GitHub](https://github.com/balamod/balamod)

- [Balamod Wiki](https://balamod.github.io/introduction.html)

- Example of a mod using [Steamodded](https://github.com/nicholassam6425/balatro-mods/blob/main/balamod/mods/quickrestart.lua), and the same mod also using [Balamod](https://github.com/nicholassam6425/balatro-mods/blob/main/steamodded/mods/quickrestart_steamodded.lua).

**Comment by Agoraaa** [comment]
Hey, thanks for the related links. I'll look into adding balamod support when I get the chance, which'll probably be this Sunday

**Comment by Agoraaa** [comment]
Done! Sorry I was busy with group projects and stuff.

**Comment by hazzuk** [comment]
I just tested the mod, and it's working perfectly with Balamod, thank you!
