### ISSUE TITLE
Outdated mod for balamod

### ISSUE THREAD

**Issue by UwUDev** [Agoraaa/FlushHotkeys#8]
Hey, balamod has been upgraded to 1.0.0+ and your mod has been removed from the in-game store because it's no longer compatible. it's very easy to update with the [docs](https://balamod.github.io/modding-basics.html), and you can also use [example-mod](https://github.com/balamod/example-mod) which has [github actions](https://github.com/balamod/example-mod/tree/main/.github/workflows) for creating releases.

If you want to add you mod back on the marketplace please follow this simple [guide](https://balamod.github.io/contributing.html#add-mods-to-the-in-game-mod-gallery)

**Comment by Agoraaa** [comment]
Merci pour prévient-moi. I updated all the code accordingly in a new branch. I'll put the PR tomorrow. 

Also I haven't really inspected it but it looks like mouse3 is not currently working for me. It might be a bug on your side
